### PR TITLE
remove memory allocation in send loop

### PR DESCRIPTION
**Pull request by sthalik**
With the changes and debug option disabled, there's none or almost none memory allocation as per Android Studio profiler. Debug allocation can't be helped since it updates text in the UI.

There's also CPU usage reduction. It was stupid high before, now it's 20%

Check at least if it works on a phone with a gyro!!! Mine has none and can't confirm for sure I got float byte order right.

### CODE REVIEW

**Comment by AndersMalmgren** [comment]
Will try it ASAP (which is later then I would like but I am super crazy busy with private life right now)

**Comment by sthalik** [comment]
Cool! The only doubtful part here is whether the floats have correct byte order.

**Comment by sthalik** [comment]
I'd rename "debug" to "troubleshooting" to discourage people from using it. Its performance implications aren't possible to go away.

**Comment by sthalik** [comment]
Or turning it off automatically on program switch/screen off or something.

**Comment by AndersMalmgren** [comment]
If you attach a debugger in any IDE it will have performance implications, but our users are not devs I they might now know that.  My point is that people should know that debug should not be used when running it for real

**Comment by AndersMalmgren** [comment]
Btw,  still haven't had time to look at the code, will lot at it latest this weekend, hope before that

**Comment by sthalik** [comment]
Sorry but I don't understand your point. Anyway we could disable the debug checkbox on our own after screen off/app going to background. Without turning it back on when it becomes foreground.

Maybe also add a scary messagebox when it's turned on but that could become annoying too much.

**Comment by sthalik** [comment]
The impact of ANY memory pressure is bad even for the continuous data send. The app stops all threads to perform a collection for up to 30-ish ms. It was happening all the time before the switch to static buffer in 	9239bdf

**Comment by AndersMalmgren** [comment]
YEah, but that was teh bug right, now its only when the debug box is checked?

**Comment by AndersMalmgren** [comment]
btw, 500 ms is to slow even for debug. I think 100 is fine, its only used when debuging right

**Comment by sthalik** [comment]
I think it's only to verify whether data is flowing but maybe have it your way. 

I'll devise some debug discouragement scheme soon-ish.

**Comment by AndersMalmgren** [comment]
It's not urgent important thing is that debug is not stealing resources when the checkbox is NOT ticked

**Comment by sthalik** [comment]
I'd leave debug refresh interval at a high value. At 100 ms it takes too little for garbage to accumulate. At 500 it's not that fast although it can never be flat. It actually is now flat when sending with no debug and UI activity.

**Comment by sthalik** [comment]
When you get around to testing this. If values sent to FreePIE are garbage, change:

    private int put_float(float f, int pos, byte[] buf)
    {
        int tmp = Float.floatToIntBits(f);
        buf[pos++] = (byte)(tmp >> 0);
        buf[pos++] = (byte)(tmp >> 8);
        buf[pos++] = (byte)(tmp >> 16);
        buf[pos++] = (byte)(tmp >> 24);
        return pos;
    }

to

    private int put_float(float f, int pos, byte[] buf)
    {
        int tmp = Float.floatToIntBits(f);
        buf[pos++] = (byte)(tmp >> 24);
        buf[pos++] = (byte)(tmp >> 16);
        buf[pos++] = (byte)(tmp >> 8);
        buf[pos++] = (byte)(tmp >> 0);
        return pos;
    }

Java APIs are already confusing as it is. The former seems to work but implies floats are bigendian even though they're little-endian. What the hell.

**Comment by AndersMalmgren** [comment]
Sorry for a late reply, it works perfect. Will release as soon as possible

**Comment by sthalik** [comment]
It's good to know it works. Please drop us a signed .apk when you're done! Thanks.

**Comment by AndersMalmgren** [comment]
I will release a new version of FreePIE in the comming days, that will include a signed version with your changes

**Pull request merged**
