### PR TITLE
add current script directory to path

### PR DESCRIPTION
**Pull request by jmriego**
Hi! Just sending my first PR to FreePIE about  #194.
This will add the directory of the currently running script to the search path for the Python libraries. It just makes a bit easier to separate your code in multiple files and reuse libraries.

Let me know if there's anything I should be changing!

### CODE REVIEW

**Comment by AndersMalmgren** [comment]
Hi, good work. One potential problem, have you tried from the GUI to run a script not yet saved?

**Comment by AndersMalmgren** [comment]
I looked at your pull in more detail. It does not build because `activeDocument` is not accessible from ConsoleHost, can be fixed by changing to args[0]. Second `scriptName` is a strange variable name, wouldnt scriptPath be better. Also its null for inmemory scripts that have yet to be saved. So it crashes.

**Comment by jmriego** [comment]
in that case I'm going to work on adding a command line option to the console script `/d` that can be followed by multiple directories that should be added to the path

it would probably take me a while to figure out how to create a gui option in which you can add additional import libraries if that would be interesting to have

**Comment by AndersMalmgren** [comment]
I'll have a look first thing tomorrow

**Comment by AndersMalmgren** [comment]
@jmriego I merged your branch manually and did some changes. Please have a look

**Comment by jmriego** [comment]
thanks a lot @AndersMalmgren ! I feel like you ended up doing more than me :)

**Pull request closed without merging**
