### PR TITLE
Issue #96: Updated vJoy dlls to version 218.

### LINKED ISSUE #96: vJoy version of Driver (218) does NOT match DLL Version (216)
Just updated to vJoy 2.1.8.31 and FreePIE 1.9.629.0 and I get the above error message in the console.

I was previously using vJoy 0.2.0.4 and FreePIE 1.7.528.0, I uninstalled both before installing the new versions.

I'm using Win 10/64.

### PR DESCRIPTION
**Pull request by MarijnS95**
Fixes #96.

See https://github.com/shauleiz/vJoy/releases/tag/v2.1.8.31 for release notes.

### Update: Newer vJoy dll's have been released in the meantime, I should probably test and update this PR with the latest version.

### CODE REVIEW

**Comment by zelmon64** [comment]
@AndersMalmgren I realised this is where the vJoy DLLs came from in #123. I just tested with [freePIE - mouse to vJoy](https://mycodestock.com/public/snippet/12603) and vJoy v2.1.8 Build 38. As far as I can tell it works fine.

@MarijnS95 Do you still want to update this PR with the latest DLLs? I tried simply copying them over but it looks like FreePIE needs to be modified to use them because it gave me an error.

**Comment by MarijnS95** [comment]
@zelmon64 Sure, I'll try to look into it this evening (in my timezone) 😉, otherwise tomorrow.

**Comment by zelmon64** [comment]
@MarijnS95 Great thanks. There's no rush.

For when you look at it: I may have gotten the error because I have a x64 installation of vJoy. I've never used it before so I may has set it up or installed it incorrectly.

**Comment by MarijnS95** [comment]
> For when you look at it: I may have gotten the error because I have a x64 installation of vJoy. I've never used it before so I may has set it up or installed it incorrectly.

IIRC I had the same issue; the vJoy dll's are 32 bit, that's probably the only incompatibility, but I'll check the C# wrapper just to be sure.

**Pull request closed without merging**
