### PR TITLE
Add support for the wiiremote speaker

### PR DESCRIPTION
**Pull request by sanjay900**
Added functions:
```python
   wiimote[i].playSoundPCM(file,volume); #Play file at volume
   wiimote[i].stopSound(); #Stop any playing sounds
```
Note that to convert a file to play on the wii remote, you need to convert it to 8bit signed pcm.
This can be done with ffmpeg using `ffmpeg -i file -ar 2000 -ac 1 -acodec pcm_s8 output.au`

Note that the sample rate is automatically detected, so you are not limited to 2000.

### CODE REVIEW

**Comment by sanjay900** [comment]
Note that if you start playing another sound, it will stop the previous sound first.

**Comment by sanjay900** [comment]
I was going to implement Yamaha ADPCM, but then realised that it wouldn't be used often, and found it didn't work correctly.

**Comment by sanjay900** [comment]
Also note that all other wiimote activity is paused if you play sounds, as all the bandwith is used and that caused the main thread to pause while it tried to update, freezing the gui and stopping the stop_sound function from working.

**Comment by sanjay900** [comment]
@zelmon64 thoughts?

**Comment by zelmon64** [comment]
@sanjay900 sorry I wasn't quite up to it yesterday.

I've built this branch, converted an audio file with ffmpeg as you instructed and ran the following script but nothing happened apart from the initial rumble. Am I missing something?
```python 
if starting:
	wiimote[0].playSoundPCM(r'C:\Users\me\Downloads\ffmpw\ffmpeg-3.4-win64-static\bin\output.au', 100); #Play file at volume
	wiimote[0].status.setLEDState(1, True)
	   
if stopping:
	wiimote[0].stopSound()
```

**Comment by sanjay900** [comment]
You might have to play it twice

**Comment by sanjay900** [comment]
@zelmon64 Fixed, just needed to immediately send the config instead of using normal methods.

**Comment by sanjay900** [comment]
@zelmon64 I think the sample rate is slightly off as sounds seem to play fast, but  it does work now.

**Comment by sanjay900** [comment]
@zelmon64 Also, just as a note, sound is stopped automatically when the script is stopped.

**Comment by zelmon64** [comment]
@sanjay900 thanks for the update. I now have sound but it's absolutely atrocious! Through win10 bt it sounds like modulated static in tune with the audio file but when connected through the dolphinbar it only sounds like static. Are the ffmpeg settings you posted initially still valid or are there any stipulations on the original file? When I play output.au with mpc-hc it sounds muffled but otherwise fine.

**Comment by sanjay900** [comment]
@zelmon64 As far as im aware, the wiimote itself just has atrocious hardware.

**Comment by sanjay900** [comment]
@zelmon64 I do not have a dolphinbar so i cant really say much about that.

**Comment by sanjay900** [comment]
@zelmon64 Even if you just hardcode it to send a single tone to the wiimote, even that has the static.

**Comment by zelmon64** [comment]
@sanjay900 fair enough. I had hoped it would be usable at least. When I used the Dolphin Emulator I think it was crackly but I could make out what it was. I'll play around with the settings and different audio files.

**Comment by zelmon64** [comment]
@sanjay900 I found some information [here](https://dolphin-emu.org/blog/2015/12/20/hey-listen-wiimoteaudio/):
> There are some limitations to this, unfortunately. Currently, only -TR Wiimotes have working Wiimote audio. Older Wii Remotes behave mostly the same as before and struggle to output any kind of recognizable audio. Secondly, Wiimote audio does not like inconsistent speed. Turning off the framelimiter will break Wiimote audio, as well as prolonged stretches of slowdown. Usually hitting the home button twice will straighten things out, but, it's worth noting that these limitations exist. It makes sense, though, it's not like a Real Wiimote would expect a Wii to be going at 6x speed! Lastly, the quality of a Bluetooth adapter does matter. In our testing, a more expensive Bluetooth adapter (~$20) **outperformed a cheap Bluetooth adapter ($5) and DolphinBar** in audio quality and latency.

I only have cheap Bluetooth adapters and the zelda wiimote I use isn't a -TR. Perhaps this is why mine seems so bad. Would you say the audio you have is usable and worth including in FreePIE?

**Comment by sanjay900** [comment]
@zelmon64 Wait how bad is it with yours? With my remote, (not tr) i can actually listen and hear the song i am playing, it just its pretty crackly.

**Comment by sanjay900** [comment]
@zelmon64 I am using a $16 adaptor though!

**Comment by sanjay900** [comment]
@zelmon64 I might borrow my friends tr of him and test with that, i am curious to see what it sounds like!

**Comment by zelmon64** [comment]
@sanjay900 yeah mine sounds almost unrecognisable. Literally just noise which fades in and out to the rhythm of the music. My bluetooth adapter was the cheapest bt4.0 I could find.

Do you use the native windows 10 bt stack or something else? Also, which bluetooth adapter do you have? I might get an ASUS USB-BT400 since it's highly recommended in general.

**Comment by sanjay900** [comment]
@zelmon64 Native windows 10 bt stack, i have a https://www.pbtech.co.nz/product/ADP8WR0400/8ware-BD-400-Mini-USB-Bluetooth-V40-Adapter-Versio

**Comment by sanjay900** [comment]
@zelmon64 So my TR remote is fake, so i cannot pair it. Dolphin can talk to it in direct mode though, and i wonder if thats something worth implementing since most fake remotes don't pair normally.

**Comment by sanjay900** [comment]
@zelmon64 Sounds like another friend has a real one i can borrow though haha

**Comment by zelmon64** [comment]
@sanjay900 thanks for the bt information.

Dolphiimote already has some pairing ability. Are they not able to be paired by pressing 1+2 when you run a FreePIE wiimote script or when you start the dolphiimote test app? If not then I agree it would be good to add more pairing features.

**Comment by zelmon64** [comment]
@sanjay900 it looks like direct mode may improve the audio quality as well. I think most people seem capable enough to use zadig to install libusbK so if you're willing to try to implement direct mode I think it would be worth it.

**Comment by sanjay900** [comment]
@zelmon64 So fake wiimotes don't implement enough if the Bluetooth stack to be discoverable by normal stacks.

**Pull request closed without merging**
