### PR TITLE
Allow WindowPlugin polling interval to be changed

### PR DESCRIPTION
**Pull request by Xuerian**

### CODE REVIEW

**Comment by AndersMalmgren** [comment]
Hi, I think pollingInterval is a better name plus please make it a property on the plugin, try to avoid public none property members

**Comment by Xuerian** [comment]
Uh, sure. What's a good plugin to reference? New to C# and the project.

**Comment by AndersMalmgren** [comment]
https://github.com/AndersMalmgren/FreePIE/blob/master/FreePIE.Core.Plugins/OculusPlugin.cs#L57

You need a public getter though

**Comment by Xuerian** [comment]
@AndersMalmgren I think I'm misunderstanding something.

Using this,
```C#
        public int pollingInterval { get; set; } = 100;

        public override void DoBeforeNextExecute()
        {
            if (timer.ElapsedMilliseconds > pollingInterval)
```
FreePIE then complains `'WindowGlobal` object has no attribute 'pollingInterval'` when I attempt to set it in a script.

**Comment by AndersMalmgren** [comment]
Yepp, but it should be pascal case :D We use camelCase on the script globals becasue camelCase is Python standard, on the internal C# code we sue the standard pascal case on properties

**Comment by AndersMalmgren** [comment]
yuo could have kept it as a property on the script global though

**Comment by Xuerian** [comment]
This is what you mean?

**Comment by AndersMalmgren** [comment]
That s it :)  can I ask why you want it, is it to go slower or faster?

**Comment by Xuerian** [comment]
I don't need it very often, it seemed like an easy way to save a little bit of CPU time. (I figured if it's throttled to 100ms by default then it has to be at least comparatively costly)

**Comment by zelmon64** [comment]
@Xuerian this has been merged, thank you. I also added the ability to return the polling interval in order to confirm it's value.

**Pull request closed without merging**
