### PR TITLE
Add support for guitar hero controllers

### PR DESCRIPTION
**Pull request by sanjay900**
https://github.com/maxmalmgren/DolphiiMote/pull/2
There are also fixes in here for the nes classic controller

### CODE REVIEW

**Comment by AndersMalmgren** [comment]
@zelmon64 Hey bud, maybe this could be a good start to look at :D

**Comment by sanjay900** [comment]
I put this together to play Clone Hero and it seems to work pretty well. I might look into implementing a bunch of other controllers too.

**Comment by zelmon64** [comment]
@AndersMalmgren I agree this is a very nice PR for me to start on.

@sanjay900 This does look to be a very well laid out PR. I've looked through it, built it and checked the Nunchuck still works as expected (I don't have a Classic Controller or Guitar). It all seems to be in order but I have a couple of questions.

1. WindowPlugin.cs looks useful but unrelated. I'm curious to know why it's here?
    - `isActive` is easy to guess its function and so is `activate` but I wasn't sure about `active` until I studied the code more carefully. I'm wondering if it would make them more obvious by renaming `activate` and `active` to `setActive` and `getActive`. That way the three functions will also be more uniform. What do you think?
2. The last commit seems to just be a merge to your master branch. I don't know how familiar you are with git but I believe this is unnecessary and could cause complications for you. In the future you can just submit the PR from your working branch. Then after it's merged into the main master branch you can update your fork's master branch from it. If I'm wrong please correct me.

**Comment by zelmon64** [comment]
@sanjay900 One more thing: what is the significance of `IsGH3`? Are there different models with different features (or this is in case a new model with different features is produced)? I'm curious when someone may want to use it.

**Comment by sanjay900** [comment]
The touch bar does not exist on world tour controllers, so its a nice way to tell if that feature is available

**Comment by sanjay900** [comment]
Also with window plugin, i have a feeling i took that from somewhere because i was using this to play games in an emulator and wanted to know if i had the game in focus.

**Comment by sanjay900** [comment]
I just realised I got that the wrong way around. gh3 controllers don't have the touch bar, world tour controllers do.

**Comment by zelmon64** [comment]
@sanjay900 thanks for the information. Do you know what happens if the touch bar is queried when a gh3 controller is connected? As in will it return 0 / false or will it give an error? If it gives an error we should probably change it to return 0 / false.

What do you think about renaming `activate` and `active` to `setActive` and `getActive`? I'm happy to do it after merging this PR unless your strongly apposed to it.

**Comment by sanjay900** [comment]
I think it's a good idea to rename. The touch bar code should currently just return zero if you are using a gh3 controller. It definitely does not error as the packet received from the wiimote is the same size regardless.

**Comment by zelmon64** [comment]
@sanjay900 thanks for your help. I realised WindowPligin.cs came from PR #79 so to preserve it's history I merged it before your PR.

I also noticed that the tapbar wan't subscribable so I added it to the class `GuitarGlobal`.

**Comment by sanjay900** [comment]
I'll have some free time now, so I'll probably work in adding the rest of the controllers I have.

**Comment by Bendito999** [comment]
Just wanted to say thanks for getting Wii Guitar hero controllers to work, I feel like I've been waiting forever for the day this would happen. Many thanks, very excited to pair it with the Midi capabilities of FreePie.

**Comment by zelmon64** [comment]
@sanjay900 what other controllers do you have (so I can keep an eye out for any cheap ones)? Do you happen to have a wii balance board?

**Comment by sanjay900** [comment]
Yeah balance board is the next step. Im half way through implementing that,
although im having issues calibrating.

**Comment by sanjay900** [comment]
Most other controllers will be easy though, because the main issue is calibration.

**Comment by AndersMalmgren** [comment]
Can I ask why vjoy dlls was included in this commit?

d8c81a311b15f2ccb2e43f9054105ae9c4790937

**Comment by sanjay900** [comment]
vjoy still works. I think I was trying to debug an app not liking vjoy or something, but it does work perfectly

**Comment by zelmon64** [comment]
@sanjay900 how's calibrating the balance board going? I've managed to get one so I can try to help if you'd like.

**Comment by sanjay900** [comment]
Theres something weird where the values arent being read from my balance board correctly, resulting in incorrect weights being registered.

**Comment by sanjay900** [comment]
Never mind, i worked out what i was doing wrong.

**Comment by sanjay900** [comment]
@zelmon64 https://github.com/AndersMalmgren/FreePIE/pull/125

**Pull request merged**
