### PR TITLE
Implement motion plus interleaving support

### PR DESCRIPTION
**Pull request by sanjay900**
We need to sleep after changing capabilities otherwise the motion plus can get into a state where the remote stops sending data back.

### CODE REVIEW

**Comment by sanjay900** [comment]
@zelmon64 With these changes i can freely change between the classic, guitar and nunchuck and then enable interleaved and it just works, and when it doesnt, i just have to hit home a few more times

**Comment by sanjay900** [comment]
Since we decided that we should just let the person scripting decide what to do when capibilities change, i just made it default to disabling the motion plus when you unplug an extension thats being passed through. That way, it works every time.

**Comment by sanjay900** [comment]
@zelmon64 
image
I have added the ability to fetch capability information from dolphiimote, and added an action so that you can be notified if capabilities change.

**Comment by sanjay900** [comment]
```
def log_motionplus():
	diagnostics.watch(wiimote[0].ahrs.yaw)
	diagnostics.watch(wiimote[0].ahrs.pitch)
	diagnostics.watch(wiimote[0].ahrs.roll)

def log_motionplus1():
	diagnostics.watch(wiimote[1].ahrs.yaw)
	diagnostics.watch(wiimote[1].ahrs.pitch)
	diagnostics.watch(wiimote[1].ahrs.roll)

def log_acceleration():
	diagnostics.watch(wiimote[0].acceleration.x)
	diagnostics.watch(wiimote[0].acceleration.y)
	diagnostics.watch(wiimote[0].acceleration.z)

def log_acceleration1():
	diagnostics.watch(wiimote[1].acceleration.x)
	diagnostics.watch(wiimote[1].acceleration.y)
	diagnostics.watch(wiimote[1].acceleration.z)

def log_nunchuck():
	diagnostics.watch(wiimote[0].nunchuck.acceleration.x)
	diagnostics.watch(wiimote[0].nunchuck.acceleration.y)
	diagnostics.watch(wiimote[0].nunchuck.acceleration.z)
	diagnostics.watch(wiimote[0].nunchuck.buttons.button_down(NunchuckButtons.C))
	diagnostics.watch(wiimote[0].nunchuck.buttons.button_down(NunchuckButtons.Z))
	diagnostics.watch(wiimote[0].nunchuck.stick.x)
	diagnostics.watch(wiimote[0].nunchuck.stick.y)

def log_classic_controller():
	diagnostics.watch(wiimote[0].classicController.buttons.button_down(ClassicControllerButtons.A))
	diagnostics.watch(wiimote[0].classicController.buttons.button_down(ClassicControllerButtons.B))
	diagnostics.watch(wiimote[0].classicController.buttons.button_down(ClassicControllerButtons.TriggerLeft))
	diagnostics.watch(wiimote[0].classicController.buttons.button_down(ClassicControllerButtons.TriggerRight))
	diagnostics.watch(wiimote[0].classicController.leftTrigger.x)
	diagnostics.watch(wiimote[0].classicController.rightTrigger.x)
	diagnostics.watch(wiimote[0].classicController.leftStick.x)
	diagnostics.watch(wiimote[0].classicController.leftStick.y)
	diagnostics.watch(wiimote[0].classicController.rightStick.x)
	diagnostics.watch(wiimote[0].classicController.rightStick.y)

def log_guitar0():
	diagnostics.watch(wiimote[0].guitar.IsGH3)
	diagnostics.watch(wiimote[0].guitar.stick.x)
	diagnostics.watch(wiimote[0].guitar.tapbar.isBlue)
	diagnostics.watch(wiimote[0].guitar.whammy.x)

def log_buttons():
	diagnostics.watch(wiimote[0].buttons.button_down(WiimoteButtons.A))
	diagnostics.watch(wiimote[0].buttons.button_down(WiimoteButtons.B))
	diagnostics.watch(wiimote[0].buttons.button_down(WiimoteButtons.Home))
	if wiimote[0].buttons.button_pressed(WiimoteButtons.A):
		wiimote[0].enable(WiimoteCapabilities.MotionPlus)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.B):
		wiimote[0].enable(WiimoteCapabilities.Extension)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.Home):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)

def log_buttons1():
	diagnostics.watch(wiimote[1].buttons.button_down(WiimoteButtons.A))
	diagnostics.watch(wiimote[1].buttons.button_down(WiimoteButtons.B))
	diagnostics.watch(wiimote[1].buttons.button_down(WiimoteButtons.Home))
	if wiimote[1].buttons.button_pressed(WiimoteButtons.A):
		wiimote[1].enable(WiimoteCapabilities.MotionPlus)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.B):
		wiimote[1].enable(WiimoteCapabilities.Extension)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.Home):
		wiimote[1].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
def log_capabilities():
	diagnostics.watch(wiimote[0].capabilities);
	if wiimote[0].capabilities.has_available_capability(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
if starting:
	# Uncomment to use the first wiimote
	
	wiimote[0].buttons.update += log_buttons
	wiimote[0].acceleration.update += log_acceleration
	wiimote[0].motionplus.update += log_motionplus
	wiimote[0].nunchuck.update += log_nunchuck
	wiimote[0].classicController.update += log_classic_controller
	wiimote[0].guitar.update += log_guitar0
	wiimote[0].capabilities.update += log_capabilities
```
Here is the current script i am using for testing.

**Comment by zelmon64** [comment]
@sanjay900 thanks for all this. I'll have a look through it today.

One thing I forgot to mention earlier was that the Dolphiimote.dll files you've been including have been debug builds. This requires extra dependencies which some people don't have. For any future versions you push could you please build the release version?

**Comment by sanjay900** [comment]
Sure, i didnt think about that one but its a pretty good point. Also, theres a small bug which im trying to debug right now where sometimes the motion plus states an extension is plugged into it when it isnt, and when thats fixed things should be good.

**Comment by sanjay900** [comment]
So my revised debugging script is:
```
def log_motionplus():
	diagnostics.watch(wiimote[0].ahrs)

def log_motionplus1():
	diagnostics.watch(wiimote[1].ahrs)

def log_acceleration():
	diagnostics.watch(wiimote[0].acceleration)

def log_acceleration1():
	diagnostics.watch(wiimote[1].acceleration)

def log_nunchuck():
	diagnostics.watch(wiimote[0].nunchuck)

def log_classic_controller():
	diagnostics.watch(wiimote[0].classicController)

def log_guitar0():
	diagnostics.watch(wiimote[0].guitar)

def log_buttons():
	diagnostics.watch(wiimote[0].buttons)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.A):
		wiimote[0].enable(WiimoteCapabilities.MotionPlus)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.B):
		wiimote[0].enable(WiimoteCapabilities.Extension)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.Home):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)

def log_buttons1():
	diagnostics.watch(wiimote[1].buttons)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.A):
		wiimote[1].enable(WiimoteCapabilities.MotionPlus)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.B):
		wiimote[1].enable(WiimoteCapabilities.Extension)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.Home):
		wiimote[1].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
def log_capabilities():
	diagnostics.watch(wiimote[0].capabilities);
	if wiimote[0].capabilities.has_available_capability(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
if starting:
	# Uncomment to use the first wiimote
	
	wiimote[0].buttons.update += log_buttons
	wiimote[0].acceleration.update += log_acceleration
	wiimote[0].motionplus.update += log_motionplus
	wiimote[0].nunchuck.update += log_nunchuck
	wiimote[0].classicController.update += log_classic_controller
	wiimote[0].guitar.update += log_guitar0
	wiimote[0].capabilities.update += log_capabilities
```

**Comment by zelmon64** [comment]
@sanjay900 thanks. I only realised about the debug build because some people reported the problem.

I found I have a forgotten classic controller pro. I tried it with your script but in passthrough mode it's being reported as a nunchuck.

**Comment by sanjay900** [comment]
What id does it have?

**Comment by zelmon64** [comment]
@sanjay900 0100A4200101 in extension only and 0100A4200505 in passthrough.

**Comment by sanjay900** [comment]
@zelmon64 That is odd since it detects your controller via extension only...

**Comment by sanjay900** [comment]
Hmm it appears i broke something somewhere...

**Comment by sanjay900** [comment]
@zelmon64 Does this commit fix anything?

**Comment by zelmon64** [comment]
@sanjay900 no it's still 0100A4200505

**Comment by sanjay900** [comment]
@zelmon64 Wait so does it show as a nunchuck on dolphiimote or freepie?

**Comment by zelmon64** [comment]
@sanjay900 in FreePIE it shows as a nunchuck when in passthrough mode and as a classic controller pro when in extension only.

**Comment by sanjay900** [comment]
@zelmon64 What does the Dolphiimote Test app say?

**Comment by sanjay900** [comment]
@zelmon64 Im just confused now because my pro is working fine haha.

**Comment by zelmon64** [comment]
@sanjay900 the Dolphiimote Test app is working correctly!

**Comment by sanjay900** [comment]
@zelmon64 hmm. Is it possible the id map is wrong or something?

**Comment by sanjay900** [comment]
@zelmon64 Does it happen with this script?
```
def log_motionplus():
	diagnostics.watch(wiimote[0].ahrs)

def log_motionplus1():
	diagnostics.watch(wiimote[1].ahrs)

def log_acceleration():
	diagnostics.watch(wiimote[0].acceleration)

def log_acceleration1():
	diagnostics.watch(wiimote[1].acceleration)

def log_nunchuck():
	diagnostics.watch(wiimote[0].nunchuck)

def log_classic_controller():
	diagnostics.watch(wiimote[0].classicController)

def log_guitar0():
	diagnostics.watch(wiimote[0].guitar)

def log_buttons():
	diagnostics.watch(wiimote[0].buttons)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.A):
		wiimote[0].enable(WiimoteCapabilities.MotionPlus)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.B):
		wiimote[0].enable(WiimoteCapabilities.Extension)
	if wiimote[0].buttons.button_pressed(WiimoteButtons.Home):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)

def log_buttons1():
	diagnostics.watch(wiimote[1].buttons)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.A):
		wiimote[1].enable(WiimoteCapabilities.MotionPlus)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.B):
		wiimote[1].enable(WiimoteCapabilities.Extension)
	if wiimote[1].buttons.button_pressed(WiimoteButtons.Home):
		wiimote[1].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
def log_capabilities():
	diagnostics.watch(wiimote[0].capabilities);
if starting:
	# Uncomment to use the first wiimote
	
	wiimote[0].buttons.update += log_buttons
	wiimote[0].acceleration.update += log_acceleration
	wiimote[0].motionplus.update += log_motionplus
	wiimote[0].nunchuck.update += log_nunchuck
	wiimote[0].classicController.update += log_classic_controller
	wiimote[0].guitar.update += log_guitar0
	wiimote[0].capabilities.update += log_capabilities
```
I have disabled the automatic switching to passthrough.

**Comment by zelmon64** [comment]
@sanjay900 FreePIE is NOW WORKING! I tried my build of Dolphiimote.dll which worked so I tried yours again and it also worked! When I tried it the first time it must have been using the previous Dolphiimote.dll.

When using the Dolphiimote Test app the mode transitions didn't seem 100% reliable with the nunchuck but it seemed perfect with the classic controller pro. FreePIE now seems 100% reliable in either case so I'm not too worried about it.

**Comment by zelmon64** [comment]
@sanjay900 You're too quick for me

**Comment by sanjay900** [comment]
@zelmon64 Anyways, now buttons shouldnt flicker which will resolve some issues.

**Comment by sanjay900** [comment]
@zelmon64 I think i'm done with changes now, i cant really think of anything i want to change at this point.

**Comment by zelmon64** [comment]
@sanjay900 there's something wrong with the toString joystick values for both the nunchuck and classic controller pro. Both the x and y values are the same.

I think it would also be better to have the nunchuck acceleration after the buttons because the length of the acceleration values quickly changes.

Do you know why the classic controller pro triggers return int values as well as booleans? The values appear to be only either 0 or 31 so they're probably redundant.

**Comment by sanjay900** [comment]
@zelmon64 With the classic controller original, the trigger value is actually a proper trigger from 0 to 31. With the pro, that functionality was removed and its just a button now.

**Comment by sanjay900** [comment]
@zelmon64 Hmm it appears it doesnt cleanly handle unplugging the motion plus.

**Comment by sanjay900** [comment]
@zelmon64 Turns out i had a 0 instead of a 1 so it was duplicating the x value.

**Comment by sanjay900** [comment]
@zelmon64 Just did a test, values seem to print correct on my guitar, classic controller and nunchuck.

**Comment by zelmon64** [comment]
@sanjay900 I was going to say the classic controller pro joystick and trigger values weren't properly symmetrical but then I ran it again to check the exact numbers and it now is all symmetrical. 

A slight problem  that remains however is that the joystick ranges are all different (+/-100ish for nunchuck, +/- 30ish for left classic controller pro joystick and +/- 15ish for the right). Could  they all be +/-100 please?

**Comment by sanjay900** [comment]
I'll have a look into it tomorrow, while i implement some status variables

**Comment by sanjay900** [comment]
@zelmon64 What was the point of determineCapabilities again? Was that because the motion plus was not triggering an unplug / replug? Because ive mostly fixed that now.

**Comment by zelmon64** [comment]
@sanjay900 I don't quite follow sorry. Are you referring to [this line](https://github.com/sanjay900/DolphiiMote/blob/203e9ad6d0b169637fd3f9f064873f56d0b88941/DolphiiMote/Core/capability_discoverer.cpp#L385)? It can be removed.

**Comment by sanjay900** [comment]
@zelmon64 No i mean in general, we have functions for determining capabilities, but i don't really see a need for that anymore since its all automatic.

**Comment by zelmon64** [comment]
@sanjay900 so you mean get rid of CapabilitiesGlobal.cs? If they don't have a potential use then sure.

**Comment by sanjay900** [comment]
@zelmon64 Cool, Thats not quite what i meant, but i think you will be able to see what i mean when i push.

**Comment by sanjay900** [comment]
@zelmon64 Okay, so i have fixed the ranges. Also, i have added the ability to get the battery status via wiimote[i].status.batteryPercentage, the ability to get the led status via wiimote[0].status.getLEDState(led), the ability to set the led status via wiimote[0].status.setLEDState(led, bool) and fixed detection of motion plus unplugging / replugging

**Comment by sanjay900** [comment]
@zelmon64 Currently i am using this script for testing:
```def log_motionplus():
	diagnostics.watch(wiimote[0].ahrs)

def log_motionplus1():
	diagnostics.watch(wiimote[1].ahrs)

def log_acceleration():
	diagnostics.watch(wiimote[0].acceleration)

def log_acceleration1():
	diagnostics.watch(wiimote[1].acceleration)

def log_nunchuck():
	diagnostics.watch(wiimote[0].nunchuck)

def log_classic_controller():
	diagnostics.watch(wiimote[0].classicController)

def log_guitar0():
	diagnostics.watch(wiimote[0].guitar)

def log_buttons():
	diagnostics.watch(wiimote[0].buttons)
	wiimote[0].setRumble(wiimote[0].buttons.button_down(WiimoteButtons.A));

def log_buttons1():
	diagnostics.watch(wiimote[1].buttons)
def log_status():
	diagnostics.watch(wiimote[0].status.batteryPercentage);
def log_capabilities():
	diagnostics.watch(wiimote[0].capabilities);
	if wiimote[0].capabilities.has_available_capability(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
	elif wiimote[0].capabilities.has_available_capability(WiimoteCapabilities.MotionPlus):
			wiimote[0].enable(WiimoteCapabilities.MotionPlus)
if starting:
	wiimote[0].buttons.update += log_buttons
	wiimote[0].acceleration.update += log_acceleration
	wiimote[0].motionplus.update += log_motionplus
	wiimote[0].nunchuck.update += log_nunchuck
	wiimote[0].classicController.update += log_classic_controller
	wiimote[0].guitar.update += log_guitar0
	wiimote[0].capabilities.update += log_capabilities
	wiimote[0].status.update += log_status
	

if keyboard.getPressed(Key.A):
		wiimote[0].status.setLEDState(1,True);
if keyboard.getPressed(Key.Z):
		wiimote[0].status.setLEDState(1,False);
		
if keyboard.getPressed(Key.S):
		wiimote[0].status.setLEDState(2,True);
if keyboard.getPressed(Key.X):
		wiimote[0].status.setLEDState(2,False);
		
if keyboard.getPressed(Key.D):
		wiimote[0].status.setLEDState(3,True);
if keyboard.getPressed(Key.C):
		wiimote[0].status.setLEDState(3,False);
		
if keyboard.getPressed(Key.F):
		wiimote[0].status.setLEDState(4,True);
if keyboard.getPressed(Key.V):
		wiimote[0].status.setLEDState(4,False);
```
Using ASDF you can enable the LEDs on the wiimote, and using ZXCV you can disable them.

**Comment by zelmon64** [comment]
@sanjay900 awesome! Do the LEDs still default to the controller number?

**Comment by sanjay900** [comment]
@zelmon64 Yeah

**Comment by sanjay900** [comment]
@zelmon64 There's probably a lot to test now though haha, since quite a bunch of things have been added to this pr.

**Comment by sanjay900** [comment]
@zelmon64 It does let me just swap between controllers though, and with my script that means that it is able to go between motion plus -> passthrough every time.

It also seems to handle unplugging the extension and the motion plus at the same time, then plugging both back in at the same time, which is something it couldn't do before.

**Comment by sanjay900** [comment]
@zelmon64 Should i be indexing leds from 0 or 1?

**Comment by sanjay900** [comment]
New script:
```python
def log_motionplus():
	diagnostics.watch(wiimote[0].ahrs)

def log_motionplus1():
	diagnostics.watch(wiimote[1].ahrs)

def log_acceleration():
	diagnostics.watch(wiimote[0].acceleration)

def log_acceleration1():
	diagnostics.watch(wiimote[1].acceleration)

def log_nunchuck():
	diagnostics.watch(wiimote[0].nunchuck)

def log_classic_controller():
	diagnostics.watch(wiimote[0].classicController)

def log_guitar0():
	diagnostics.watch(wiimote[0].guitar)

def log_buttons():
	diagnostics.watch(wiimote[0].buttons)
	wiimote[0].setRumble(wiimote[0].buttons.button_down(WiimoteButtons.A));

def log_buttons1():
	diagnostics.watch(wiimote[1].buttons)
def log_status():
	diagnostics.watch(wiimote[0].status.batteryPercentage);
def log_capabilities():
	diagnostics.watch(wiimote[0].capabilities);
	if wiimote[0].capabilities.has_available_capability(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus):
		wiimote[0].enable(WiimoteCapabilities.Extension | WiimoteCapabilities.MotionPlus)
	elif wiimote[0].capabilities.has_available_capability(WiimoteCapabilities.MotionPlus):
			wiimote[0].enable(WiimoteCapabilities.MotionPlus)
if starting:
	wiimote[0].buttons.update += log_buttons
	wiimote[0].acceleration.update += log_acceleration
	wiimote[0].motionplus.update += log_motionplus
	wiimote[0].nunchuck.update += log_nunchuck
	wiimote[0].classicController.update += log_classic_controller
	wiimote[0].guitar.update += log_guitar0
	wiimote[0].capabilities.update += log_capabilities
	wiimote[0].status.update += log_status
wiimote[0].status.setLEDState(0,keyboard.getKeyDown(Key.A));
wiimote[0].status.setLEDState(1,keyboard.getKeyDown(Key.S));
wiimote[0].status.setLEDState(2,keyboard.getKeyDown(Key.D));
wiimote[0].status.setLEDState(3,keyboard.getKeyDown(Key.F));

diagnostics.watch(wiimote[0].status.getLEDState(0));
diagnostics.watch(wiimote[0].status.getLEDState(1));
diagnostics.watch(wiimote[0].status.getLEDState(2));
diagnostics.watch(wiimote[0].status.getLEDState(3));
```

**Comment by zelmon64** [comment]
@sanjay900 I agree the LEDs should be indexed from 0.

That last script you posted, did you do something differently to make it use colours? It's nice.

**Comment by sanjay900** [comment]
@zelmon64 also I feel I forgot to mention wiimote.setRumble(state) is a thing now too.

**Comment by sanjay900** [comment]
@zelmon64 When you type the backticks, you can just put python next to it.
e.g
````python
```python

code

```
````

**Comment by sanjay900** [comment]
@zelmon64 I think i'm done now though in terms of features.

**Comment by zelmon64** [comment]
@sanjay900 great thanks! I'll check through it all then merge.

**Comment by zelmon64** [comment]
@sanjay900 I couldn't see any problems. The new LED and battery level features are very impressive! 

Have you considered trying to implement speaker control? Just basic beeps could be quite useful but it does look a bit daunting.

**Comment by sanjay900** [comment]
@zelmon That was my next plan actually haha

**Comment by sanjay900** [comment]
@zelmon64 Ive managed to get it to play audio but it doesn't sound right. I wonder what the best way to deal with audio files will be, since the remote does want you to throw data at it in a specific way. Im currently converting with ffmpeg.

**Comment by zelmon64** [comment]
@sanjay900 what format and sample rate are you using? Is it 4-bit ADPCM since you're converting with ffmpeg? Wiibrew recommends 8-bit PCM at 2000Hz, have you tried that already?

Whole audio files may just be too much for it. Perhaps implementing simple frequencies might be easier?

**Comment by sanjay900** [comment]
Yeah I've used both. I'm trying to find singing that would actually sound okay on the speaker, since most sounds don't sound good after being converted.

**Comment by sanjay900** [comment]
@zelmon64 It does seem to work though about as well as it should

**Comment by sanjay900** [comment]
@zelmon64 Oh my code was playing samples in reverse, no wonder it sounded wrong

**Pull request merged**
