### PR TITLE
Android sensor fixes

### PR DESCRIPTION
**Pull request by sthalik**
Non-critical fixes for the Android app.

Refused to register events with no checkboxes selected at start.  Refused to send raw data only.

### CODE REVIEW

**Comment by sthalik** [comment]
The sensor register stuff is important though, many devices disable accelerometer events with the screen off. New code works around it.

**Comment by sthalik** [comment]
In their present shape, checkbox settings don't provide information to the user. "Game", "UI" names are arbitrary. At the very least we should provide the delay those constants signify.

Whether rate setting is useful or not - Android API only allows for several predefined rates. As per information in the commit, only the two fastest rates seem sensible at all. For that I fail to see a use-case, are there users depending on this behavior?

In any case it's very important we reregister sensors. Multiple users reported issues when screen goes off, it even happens on my Galaxy Core.

**Comment by AndersMalmgren** [comment]
I think we should revert that behaviour so the user can choose,  the default for it is still Game. 

Also,  the checkbooks for selecting which data to transfer is gone.  It's just data overhead if the user isn't using it

**Comment by sthalik** [comment]
Checkboxes should be there, as they're in the activity layout.

**Comment by AndersMalmgren** [comment]
Cool will have a look at everything this weekend :)

**Comment by sthalik** [comment]
@AndersMalmgren could you take a look sometime?

**Comment by AndersMalmgren** [comment]
Super sorry, work and life happened, will try to look at it this weekend :/

**Comment by AndersMalmgren** [comment]
Signed version here

http://www.mtbs3d.com/phpBB/viewtopic.php?f=139&t=15490&p=158238#p158238

**Comment by sthalik** [comment]
@AndersMalmgren thanks a lot!

**Pull request merged**
